### ISSUE TITLE
Accept implicit encodings.

### ISSUE THREAD

**Issue by CharString** [tk0miya/flake8-coding#11]
As I understand it currently I can either enforce all files to have a coding magic comment by using the default or some other `accept-encodings`:

```ini
[flake8]
accept-encodings = latin-1,utf-8
```

or I can force all files to have *no* coding magic comment with

```ini
[flake8]
no-accept-encodings = True
```

What if I want to accept the implicit encoding too?
I did not expect a C101 when I have this config:

```ini
[flake8]
accept-encodings = utf-8,ascii
```

Because they are the default implicit encodings that resp. Python 3 and 2.7 use when no magic comment is present.

Is there a reason why I shouldn't want this behaviour?

**Comment by tk0miya** [comment]
Did you mean some files have implicit encoding and others have explicit one?
This plugin enforces all of files are implicit or explicit, not mixed.

**Comment by CharString** [comment]
Exactly

**Comment by tk0miya** [comment]
I think that's not use case of this plugin.
